// generated by dashboard_snapshot.py (read-only, no secrets)
window.POSITIONS_SNAPSHOT = {
  "generated_et": "2026-10-08 13:26:03 EDT",
  "state_updated_et": "2026-10-08 13:25:34 EDT",
  "read_only_note": "Snapshot from state.json only. No keys, no signing.",
  "params": {
    "mcap_min": 200000.0,
    "mcap_max": 1000000.0,
    "max_positions": 2,
    "buy_usd": 500.0,
    "tp_multiple": 1.4,
    "early_exit_prefer_multiple": 1.2,
    "early_exit_mode": "first_slowdown_immediate_full_sell",
    "new_buys_paused_until": null
  },
  "exclude_mints": [
    "41MjNbWHZeFmxwMHPwTfsJP3aPbvsvR5tsgnmhNKpump",
    "75gGuxuqKhQQiHae8JKDQaetK3XguKf1rUJ1csispump",
    "85WdpEBNDSN9oNkPomBGspnBZsaKb7WF1NQ51pdouxML",
    "CioPfvQWpVF2eTzpBj72x2zPyqgJRgvi36PqdLCCpump",
    "DEQKHY5YVPFiwcVhoUUE5gnkWj66LVPoPgLHAswqpump",
    "HMYd9tosnUXuNHmq7pXmoePRVBLBBjA3JBfydq6upump",
    "HbPDWSqu8hpVMX6gMjwMDGe5rVgicWo3Qh3Jaojypump",
    "MRVLSjkR2ceUBukujaD3xCyHP1H3B2SzpsNTZF546jo",
    "RACEyWiM2ztEZcJx2AHXU2eWjhxU57x3vXn92b39dLD"
  ],
  "exclude_symbols": [
    "ART",
    "ATTENTION",
    "ATTENTION+",
    "FRANK",
    "FRENS",
    "HASHERS",
    "MRVL",
    "RACE",
    "SI276",
    "TON618",
    "TWEETCRAFT"
  ],
  "open_organic_count": 1,
  "positions": [
    {
      "mint": "2bN9YoTKiejNonS4Q1EjhypvRfndZLEiYJZUHLwYpump",
      "symbol": "PANDA",
      "name": "Pandacoin",
      "status": "open",
      "entry_et": "2026-10-08 12:58:57 EDT",
      "cost_usd": 433.5813659407999,
      "tokens_ui": 1586825.592424,
      "entry_price_usd": 0.0002732381983318473,
      "entry_mc": 253236.2633777806,
      "tp_multiple": 1.4,
      "tp_target_usd": 607.0139123171199,
      "tp_target_mc": 354530.7687288928,
      "last_bag_usd": 419.55668663690557,
      "last_mult": 0.9676538698256483,
      "last_check_et": "2026-10-08 13:25:34 EDT",
      "exit_reason": "first_slowdown:hc5_stall=-0.059%,holders_flat_or_down=1687->1681,holders_off_peak=1687->1681",
      "pnl_usd": null
    }
  ],
  "history": [
    {
      "mint": "85WdpEBNDSN9oNkPomBGspnBZsaKb7WF1NQ51pdouxML",
      "symbol": "HASHERS",
      "name": "hashers.network",
      "status": "moonbag",
      "entry_et": "2026-10-07 08:56:33 EDT",
      "cost_usd": 494.18525,
      "tokens_ui": 174.982833,
      "entry_price_usd": 0.0003683729691824626,
      "entry_mc": 322069.253743492,
      "tp_multiple": 1.8,
      "tp_target_usd": 889.53345,
      "tp_target_mc": 579724.6567382857,
      "last_bag_usd": 235.97601567388858,
      "last_mult": 0.47750517781315527,
      "last_check_et": "2026-10-07 10:01:26 EDT",
      "exit_reason": null,
      "pnl_usd": null
    },
    {
      "mint": "DEQKHY5YVPFiwcVhoUUE5gnkWj66LVPoPgLHAswqpump",
      "symbol": "ART",
      "name": "ArtCoin",
      "status": "moonbag",
      "entry_et": "2026-10-07 09:33:04 EDT",
      "cost_usd": 499.99999990536,
      "tokens_ui": 29796.460157,
      "entry_price_usd": 0.0002854908338369892,
      "entry_mc": 263495.33947223576,
      "tp_multiple": 1.8,
      "tp_target_usd": 899.9999998296481,
      "tp_target_mc": 474291.6110500244,
      "last_bag_usd": 925.5988936613825,
      "last_mult": 1.8511977876731596,
      "last_check_et": "2026-10-07 10:00:40 EDT",
      "exit_reason": null,
      "pnl_usd": null
    },
    {
      "mint": "CioPfvQWpVF2eTzpBj72x2zPyqgJRgvi36PqdLCCpump",
      "symbol": "TON618",
      "name": "TON 618",
      "status": "closed",
      "entry_et": "2026-10-07 11:58:33 EDT",
      "cost_usd": 500.18199442375004,
      "tokens_ui": 0.0,
      "entry_price_usd": 0.0004862015248977261,
      "entry_mc": 409003.40397042996,
      "tp_multiple": 1.8,
      "tp_target_usd": 900.32758996275,
      "tp_target_mc": 736206.127146774,
      "last_bag_usd": 437.220651816775,
      "last_mult": 0.8741231325619556,
      "last_check_et": "2026-10-07 13:30:53 EDT",
      "exit_reason": "holders_soft_early_exit (1419@13:26 -> 1413 -> 1409@13:30, 5m holderChange -0.63%)",
      "pnl_usd": -47.85
    },
    {
      "mint": "AHmD5jaFKqWMGswNkTSwAfvaWNHVY8m6JJro9LFppump",
      "symbol": "FLY",
      "name": "fly-42 project",
      "status": "closed",
      "entry_et": "2026-10-07 15:02:03 EDT",
      "cost_usd": 429.07202747802,
      "tokens_ui": 0.0,
      "entry_price_usd": 0.00044772435759941355,
      "entry_mc": 447724.35759941355,
      "tp_multiple": 1.8,
      "tp_target_usd": 772.329649460436,
      "tp_target_mc": 805903.8436789444,
      "last_bag_usd": 760.538387574656,
      "last_mult": 1.7725191549887647,
      "last_check_et": "2026-10-07 15:10:56 EDT",
      "exit_reason": null,
      "pnl_usd": null
    }
  ],
  "last_decision": {
    "last_skip_reason": "2026-10-07 20:28 EDT skip: Sol cash 0.0765 SOL (below 0.08 gas reserve) after owner manual LOADED buy; 0 open organic; no sells. No scan buy possible.",
    "last_scan_et": "2026-10-08 13:18:00 EDT",
    "last_scan_n_in_band": 1,
    "last_scan_best": {
      "symbol": "SENTS",
      "mint": "BLXhcFAtJpCM3HCbdzvr8F3JwGqdMGkAoLXuRmXLpump",
      "mcap": 361865.45638955507
    },
    "last_buy": {
      "as_of_et": null,
      "symbol": "PANDA",
      "mint": "2bN9YoTKiejNonS4Q1EjhypvRfndZLEiYJZUHLwYpump",
      "cost_usd": 433.5813659407999
    }
  },
  "cash_snapshot": {
    "sol_native": 0.076507437,
    "sol_usd_approx": 43.42758466689,
    "arc_usdc": 633.2829376602017,
    "available_buy_usd_approx": 0,
    "as_of_et": "2026-10-07 20:28 EDT",
    "note": "after manual LOADED buy (~4.26 SOL); organic loop has no cash"
  },
  "recent_notes": [
    {
      "et": "2026-10-07 10:03:16 EDT",
      "event": "owner_sell_bridge_resume",
      "detail": "HASHERS full bag sold (57bTRX + dust 2sWLo); ART moonbag TP sold (3QniXG + 2e8Va8); SOL proceeds Relay\u2192Arc USDC +1132.87 (Arc now ~1143); Frank HOLD 5x; organic scanner RESUMED max2 Sol-cash-only 200-500k MC; cleared new_buys_paused / HASHERS hold"
    },
    {
      "et": "2026-10-07 10:04:35 EDT",
      "event": "owner_correction_bridge_hashers_proceeds_back_to_sol",
      "detail": "HASHERS sell proceeds should have stayed on Sol; were bridged to Arc with ART. Bridged $510 Arc USDC \u2192 Sol via Relay. Frank HOLD 5x. Organic can buy again ($500, max2, 200-500k MC, Sol cash only)."
    },
    {
      "et": "2026-10-07 10:07:43 EDT",
      "event": "owner_strategy_change_1_8x_full_sell",
      "detail": "TP 2.3x moonbag \u2192 1.8x FULL SELL. After sells leave ~$500 Sol cash, Relay excess to Arc USDC 8488. Max2, buy $500, MC 200-500k, Sol cash only, no Jupiter. Frank SEPARATE hold 5x \u2014 do not sell."
    },
    {
      "et": "2026-10-07 11:04:27 EDT",
      "event": "routine_skip",
      "detail": "routine 11:03 run: 0 open organic positions, no TP sells. Skipped buy: live owner scan OWNER_SCAN_1103.json verdict NOTHING_GREAT_IN_BAND (AI = 40-min bot/sniper heat ~4% organic vol; TON618 wash-heavy; slopcannon fading; KOMO thin); parent awaiting owner greenlight. Sol ~4.47 SOL (~$517) kept for next buy. No bridge (no excess)."
    },
    {
      "et": "2026-10-07 11:59:06 EDT",
      "event": "buy_filled",
      "symbol": "TON618",
      "detail": "11:56 routine: 0 open, top in-band TON618 ~$409-416k MC, holders +12%/1h +63%/6h, 927 holders, org 65.7"
    },
    {
      "et": "10/7/2026, 13:31:12 ET",
      "event": "ton618_holders_soft_full_sell"
    },
    {
      "et": "2026-10-07 13:38:07 EDT",
      "event": "owner_tighten_early_exit_first_slowdown",
      "detail": "On open organic bags: sell immediately on FIRST notice of holder-growth slowdown/deceleration/stall \u2014 do not wait for clear decline. Prefer ~1.2x exit over riding to a loss. Still full sell at 1.8x if growth stays strong. Frank = 5x hold only. Encoded in STRATEGY.md, state.json early_exit_policy, tp_check.py flip logic, ARM_STATUS.json. TON618 already sold; 0 open organic."
    },
    {
      "et": "2026-10-07 14:50:50 EDT",
      "event": "owner_dynamic_buy_size_and_rising_holders_entry",
      "detail": "Buy size DYNAMIC: target $500; if Sol cash < $500 spend available SOL minus gas reserve (~0.05-0.1 SOL). Not fixed $425. HARD entry: never buy falling/flat holders \u2014 only clearly rising (hc1>0 and hc5>0). Sol bal 4.068276 (~$473.14); next run may buy ~$463.84. No buy this pass. Frank untouched 5x."
    },
    {
      "et": "2026-10-07 15:06:24 EDT",
      "event": "tp_due",
      "symbol": "FLY",
      "reason": "tp_1_8x_growth_strong"
    },
    {
      "et": "2026-10-07 15:17:08 EDT",
      "event": "owner_strategy_change_1_4x_full_sell_sdk_autosell",
      "detail": "TP 1.8x \u2192 1.4x FULL SELL. Keep early exit on FIRST holder-growth slowdown (prefer ~1.2x). tp_check auto-sell now primary PumpSwap SDK sell_pumpswap_tp.mjs + landing_guard; PumpPortal sell_moonbag_tp.mjs fallback only after SDK fail. No open organic (FLY sold). Frank 5x watcher untouched. No buy/sell this pass. No Jupiter."
    },
    {
      "et": "2026-10-07 19:47:20 EDT",
      "event": "manual_buy_filled",
      "symbol": "FRENS",
      "detail": "Owner manual buy, separate from organic loop; not in positions[]; own 5x watcher"
    },
    {
      "et": "2026-10-08 13:05:10 EDT",
      "event": "early_exit_due",
      "symbol": "PANDA",
      "reason": "early_first_slowdown@0.964x:first_slowdown:hc5_stall=-0.059%,holders_flat_or_down=1687->1681,holders_off_peak=1687->1681"
    }
  ]
};
